### ISSUE TITLE
Control Pannel not opening

### ISSUE THREAD

**Issue by sosauce** [Rectify11/Installer#464] opened 2024-02-08 00:52 UTC
### Description

Control pannel simply won't open after installing rectify11

### Steps To Reproduce

Install Rectify11

### Rectify11 Version

3.1

### Windows Version

Win11 23h2

### Logs

Dont have

**Comment by MishaProductions** [comment] 2024-02-09 18:20
Before opening issues, please read the existing issues.  Duplicate of #466 #460 #356 #405

**Closed by MishaProductions** 2024-02-09 18:20 UTC
Labels: bug
