### ISSUE TITLE
light theme word

### ISSUE THREAD

**Issue by ISIN11** [Rectify11/Installer#557] opened 2024-06-08 15:23 UTC
### Description

How can I fix the display of a LIGHT theme in a word? 
I read thread 175, but there is a solution with a BLACK word theme, how can I adequately use a LIGHT theme with a white sheet?

### Steps To Reproduce

Launch a word 

### Rectify11 Version

3.2.70.1

### Windows Version

Windows 11 Pro 22H2 22621.3672

### Logs

![WINWORD_HcDHiuzhQa](https://github.com/Rectify11/Installer/assets/69667998/fd2986eb-e6c7-4c4c-956f-8917eef50092)
![WINWORD_NlBtgXPsTD](https://github.com/Rectify11/Installer/assets/69667998/334b962d-3acf-417c-a049-6e3efed1ea07)
![WINWORD_1aDdNyN6dV](https://github.com/Rectify11/Installer/assets/69667998/702b99b9-e5a5-4e2f-9ef4-f702d24700da)

**Comment by PokenDev21** [comment] 2024-07-12 14:55
Very sad that they just keep closing these issues without fixing it but i found another shit workaround which is to open the rectify control panel and set the theme to Rectify 11 light theme, after that go into windows settings and set the theme back to dark. This basically eliminates what rectify is trying to do and now you have a light control panel etc but it works for word.

**Comment by ooTruffle** [comment] 2024-07-13 05:49
The issue is that microsoft hardcoded certan things



You could use Rectify 11 Partal dark theme

**Comment by MishaProductions** [comment] 2024-08-09 18:32
use partial dark theme

**Closed by MishaProductions** 2024-08-09 18:32 UTC
Labels: bug
