### ISSUE TITLE
Issue with consistent dark mode and AccentColorizer

### ISSUE THREAD

**Issue by ShashankKalwa** [Rectify11/Installer#373] opened 2023-11-15 15:14 UTC
I have tried the **3.0 and 3.1 versions**, but there is a problem with **consistent dark mode**. the **control panel**, the **run**, the **service**, and more are not in the _dark mode_ and the **accent-colorizer** doesn't work.
I don't why, I think it needs optimization because it made my PC a bit slower, I have noticed it at the time of login and when opening settings.
Please fix these issues.
Thank You!
![Screenshot 2023-11-15 201801](https://github.com/Rectify11/Installer/assets/93568767/1f8ce07a-9bcf-421f-96a9-9a9719fdad5d)
![Screenshot 2023-11-15 203840](https://github.com/Rectify11/Installer/assets/93568767/2801ae3a-0cd2-41bf-a7e1-8dc28698db82)
![Screenshot 2023-11-15 204022](https://github.com/Rectify11/Installer/assets/93568767/fe6d81f0-84ef-4ece-8c10-ecc7a4e01f04)

**Comment by MishaProductions** [comment] 2024-03-29 19:54
duplicate of #502 502

**Closed by MishaProductions** 2024-03-29 19:54 UTC
