### ISSUE TITLE
Right-Click context menu bug

### ISSUE THREAD

**Issue by bagassw-exe** [Rectify11/Installer#636] opened 2024-10-06 01:30 UTC
### Description

when i right click on taskbar or in menu, it shows white context bar instead when i set theme in black mica, and it has broken context menu in taskbar.

### Steps To Reproduce

Right Click on Desktop & Right Click on taskbar

### Rectify11 Version

Version 3.2

### Windows Version

Windows 11 24H2

### Logs

![image](https://github.com/user-attachments/assets/46f22ab8-3e12-450b-9a06-745ecdd227f5) 
![image](https://github.com/user-attachments/assets/1c62c7ce-8b8c-4d08-856b-e2922248d22c)

**Comment by willyblah** [comment] 2024-10-07 02:15
Me too

**Comment by NotAsea** [comment] 2024-10-09 10:03
+1 i also have same problem on Window 11 24H2, have to change back to default Window 11 context menu

**Comment by bagassw-exe** [comment] 2024-10-09 10:10
> +1 i also have same problem on Window 11 24H2, have to change back to default Window 11 context menu

is it works?

**Comment by NotAsea** [comment] 2024-10-09 10:29
> > +1 i also have same problem on Window 11 24H2, have to change back to default Window 11 context menu
> 
> is it works?

Yes it work, the problem is they use stable Nirshell which still hasnt supported Window 11 24H2 yet

**Comment by izmare** [comment] 2024-10-12 16:33
The "Select far right corner of taskbar to show the desktop" doesn't work anymore. Right click Task bar show desktop also does nothing. Anyone else or just me ?!? This is driving me nuts.

**Comment by MishaProductions** [comment] 2024-10-12 23:53
should be fixed by 60ba41941bee153d658b7a087783177a50fa213b

**Closed by MishaProductions** 2024-10-12 23:53 UTC
Labels: bug
