### ISSUE TITLE
White patches in dark with mica theme

### ISSUE THREAD

**Issue by wildgamharsh** [Rectify11/Installer#170] opened 2023-06-12 17:29 UTC
### Description

the dark with mica theme have white areas which are not readable and look very annoying please help
also the drives have rounded border but once i change the theme those rounded corners disappear resulting in a very bad appearence

### Steps To Reproduce

fix the white part in dark with mica theme 
fix the theme changing mechanism

### Rectify11 Version

V3 rp3

### Windows Version

Windows 11 22H2 Build 22621

### Logs

i have no log

**Comment by Typical0** [comment] 2023-06-12 17:33
Duplicate of #159 and #153. The issue was already fixed in the newest commits.

**Closed** 2023-09-08 09:28 UTC
Labels: bug
