### ISSUE TITLE
Returning a control panel from "Rectify11 Setting" results in an unresponsive response

### ISSUE THREAD

**Issue by wangyan-life** [Rectify11/Installer#466] opened 2024-02-09 08:35 UTC
### Description

Clicking on "All Control Panel Items" or "Control Panel" from "Rectify11 Setting" in the Control Panel to return to the Control Panel home page will get stuck.

### Steps To Reproduce

1. Open the control panel
2. Click on "Rectify11 Setting".
3. Click "All Control Panel Items" or "Control Panel".
4. Prolonged unresponsiveness

### Rectify11 Version

v3.1

### Windows Version

Windows 11 23H2 22631.3085

### Logs

![屏幕截图(10)](https://github.com/Rectify11/Installer/assets/105880463/7b47ba68-9b42-4070-9958-099105980bae)

![屏幕截图(11)](https://github.com/Rectify11/Installer/assets/105880463/85739fcf-271c-4143-b648-b0dee2827b08)

![屏幕截图(9)](https://github.com/Rectify11/Installer/assets/105880463/f4321a29-c7e4-4e6a-895e-3e5b42b7417d)

**Comment by MishaProductions** [comment] 2024-02-09 18:20
Before opening issues, please read the existing issues. Duplicate of #466 #460 #356 #405

**Closed by MishaProductions** 2024-02-09 18:20 UTC
Labels: bug
