### ISSUE TITLE
HDR on LG Moniors problem ? or not?

### ISSUE THREAD

**Issue by NeverMoreCreations** [Rectify11/Installer#463] opened 2024-02-07 11:41 UTC
### Description

the color of the words on the LG monitor or more if hdr is enabled not work and accents and words or windows fonts is dark on dark theme if HDR is turned off, the problem is solved and the control panel program go to random reset and the modifyes if fixed after restart on certain cases is reset and bad words and more in my head xD

### Steps To Reproduce

only installl Rectify 11 on my pc and use dark theme

### Rectify11 Version

3.1 and both before

### Windows Version

32h2v2 and last insider preview, on next days i test the beta branch and update here my vision

### Logs

i add this soon, sorry no time now i need fix a problem on my life :)

**Comment by MishaProductions** [comment] 2024-02-07 17:46
Duplicate of #440 #400

**Closed by MishaProductions** 2024-02-07 17:46 UTC
Labels: bug
