### ISSUE TITLE
new bug bro

### ISSUE THREAD

**Issue by XenonJGR** [Rectify11/Installer#267] opened 2023-09-13 00:17 UTC
### Description

selecting on device manager barely shows anything makes things hard to navigate

### Steps To Reproduce

just go in device manager on your pc (its autimatically installed) and try selecting something (click on it). Nothing happens except you can see a little dot or something.

### Rectify11 Version

3.0.40.0

### Windows Version

Windows 11 Version 22H2 for x64-based Systems (KB5030219)

### Logs

no logs

**Comment by WildByDesign** [comment] 2023-09-14 10:58
This sounds like a duplicate of this issue: https://github.com/Rectify11/Installer/issues/253

Try the steps here to see if it fixes the problem for you: https://github.com/Rectify11/Installer/issues/253#issuecomment-1713750138

**Comment by YT-Advanced** [comment] 2023-10-01 10:23
@WildByDesign Can you take a screenshot of Device Manager after apply the fix

**Comment by WildByDesign** [comment] 2023-10-01 11:34
@YT-Advanced For sure.
![devicemanager1](https://github.com/Rectify11/Installer/assets/26308319/d4424a09-1f01-400e-815f-6a54d661d9a8)
![devicemanager2](https://github.com/Rectify11/Installer/assets/26308319/0bb2545d-a4bc-41d7-8fea-cb7bc76396ee)

**Comment by YT-Advanced** [comment] 2023-10-01 11:38
> @YT-Advanced For sure.
> ![devicemanager1](https://github.com/Rectify11/Installer/assets/26308319/d4424a09-1f01-400e-815f-6a54d661d9a8)
> ![devicemanager2](https://github.com/Rectify11/Installer/assets/26308319/0bb2545d-a4bc-41d7-8fea-cb7bc76396ee)
> 
> 

Is the Device Manager still scale ?

**Comment by WildByDesign** [comment] 2023-10-01 12:00
> Is the Device Manager still scale ?

As far as I can tell, yes. I have it set to force DPI awareness and shows in System Informer as Per-Monitor V2.

It's sharp and crisp, displaying much better in comparison to default Microsoft's GDI Scaling.

The screenshots never seems sharp on Github issues though for some reason as if it's stretching them or something.

**Comment by YT-Advanced** [comment] 2023-10-01 12:12
Wow, I will test it

**Comment by WildByDesign** [comment] 2023-10-01 12:28
Please let me know how your experience goes. I believe that the Rectify11 devs should add this to the project but it would be good if a few more users test it first.

**Comment by YT-Advanced** [comment] 2023-10-07 14:10
@WildByDesign Your way disabled the GDI for mmc.exe and currently in latest Rectify11 already have a fix for it (if I remembered correctly)

**Comment by WildByDesign** [comment] 2023-10-07 14:44
@YT-Advanced I can’t seem to find the fix for it. I use the latest Actions builds and all of my MMC-related tools are still messed up unless I use my fix.

**Comment by rounk-ctrl** [comment] 2023-10-07 15:59
ill add it

**Comment by WildByDesign** [comment] 2023-10-07 19:31
> ill add it

Thanks, man.

**Comment by rounk-ctrl** [comment] 2023-10-08 16:16
#253

**Closed by rounk-ctrl** 2023-10-08 16:16 UTC
Labels: bug
