### ISSUE TITLE
Icons in the explorer 

### ISSUE THREAD

**Issue by fadi9711** [Rectify11/Installer#558] opened 2024-06-08 15:25 UTC
### Description

the icon that changes the view of the file in File Explorer shows square  

### Steps To Reproduce

just open the file explorer and you will see it 
I uploaded a screenshot

### Rectify11 Version

version 3.2.70.1

### Windows Version

windows 11 23H2 22631.2861

### Logs

![Screenshot 2024-06-08 082228](https://github.com/Rectify11/Installer/assets/68429224/7d9f655f-926e-48df-96e2-b824f94cac6c)

**Comment by wDRxxx** [comment] 2024-07-11 09:42
I have the same problem. Have you fixed this?

**Comment by MishaProductions** [comment] 2024-08-09 18:32
Duplicate of #586

**Closed by MishaProductions** 2024-08-09 18:32 UTC
Labels: bug
