### ISSUE TITLE
Office Applications Color broken

### ISSUE THREAD

**Issue by pizzacom123456** [Rectify11/Installer#259] opened 2023-09-02 12:20 UTC
### Description

When I run applications like Word in the normal light theme. Everything looks great exept the main page. It's completely black only when I change the Design to dark mode in word the page returns white. Using Dark theme with mica and without. Problem stays the same.
![Screenshot 2023-09-02 141732](https://github.com/Rectify11/Installer/assets/115363308/51c284ed-2a24-4614-861c-0c986b4a7c4f)
![Screenshot 2023-09-02 141848](https://github.com/Rectify11/Installer/assets/115363308/09233859-e7ec-49fb-8f22-e7d3ba9479eb)

### Steps To Reproduce

.

### Rectify11 Version

newest Version

### Windows Version

fresh windows install 22H2 Build 22621.2215

### Logs

.

**Comment by SmirbYrneh420** [comment] 2023-09-02 13:50
Duplicate of #200 
Go to File > Options and make sure your settings look like this (most important option is "Never change the document page color"
![image](https://github.com/Rectify11/Installer/assets/110212580/2590cd10-bc56-4f1d-aec6-5c432d1a98a5)

**Comment by pizzacom123456** [comment] 2023-09-02 14:49
WIth this option the page is black on dark mode but also black in light mode. Is there any way to make the page white?

**Comment by rounk-ctrl** [comment] 2023-09-03 07:22
view -> switch modes

**Comment by pizzacom123456** [comment] 2023-09-03 14:08
Thanks for the suggestion but this does not work, as the button for this is only available on black mode. On gray or white mode there is no such button. Is there any way at the moment to change the page color to white in white mode?

**Comment by TheBeeBoi** [comment] 2023-09-05 12:31
Same for me.
![image](https://github.com/Rectify11/Installer/assets/97726243/e92a3acc-b207-495d-b39a-aaa71fe4308d)

**Comment by TheBeeBoi** [comment] 2023-09-05 12:33
okay so i figured it out. the problem is only for the text, and not for the background

**Comment by bbecausereasonss** [comment] 2023-09-26 18:36
Yep... unusable.

**Comment by BetterWin11Project** [comment] 2023-09-27 11:17
Fixes:
[Excel](https://github.com/matafokka/ExcelDarkThemeFix)
[Word](https://github.com/Rectify11/Installer/issues/200#issuecomment-1668170778)
[PowerPoint](https://github.com/matafokka/PowerPointDarkThemeFix)

**Closed** 2023-10-08 16:12 UTC
Labels: bug
