### ISSUE TITLE
Colours bugging on System and Chrome

### ISSUE THREAD

**Issue by brenio55** [Rectify11/Installer#263] opened 2023-09-06 06:36 UTC
### Description

Some pages that are originally with the input entries white and the texts black are not showed correctly, with the texts becoming white suddenly, but this only started to happen when I installed Rectify11 RC1. This happens too with some other pages around the internet. I'll install RC2 now and see if this bug is corrected. I'll give you guys a feedback soon if it does.

### Rectify11 Version

RC1

### Windows Version

Windows 11 22H2 22621.2215

**Comment by brenio55** [comment] 2023-09-09 03:07
![image](https://github.com/Rectify11/Installer/assets/65581387/e1254298-f0cd-49e8-a656-3f52feb9e768)
Here's a proper image from the Bug I'm talking about. Some parts that should be black and white are only white and vice-versa. This is the current RC2, needs to be solved urgently

**Comment by TiagoRibeiro25** [comment] 2023-09-09 11:50
For me, this can be fixed by patching the icons but for some reason my antivirus (ESET) stops working after re-booting, so I need to stay with these annoying white areas.

**Comment by brenio55** [comment] 2023-09-10 04:17
![image](https://github.com/Rectify11/Installer/assets/65581387/ae449532-791d-457d-8063-5a080825ef4c)
Another screenshot, this time on a website, of the bug said before.

**Comment by es1228** [comment] 2023-09-10 14:44
I think it’s because some colours are hardcoded and cannot be changed, while the ones that are not hardcoded are getting changed

**Comment by brenio55** [comment] 2023-09-11 02:42
I don't believe that's the case, you mean a !important on the colour?

**Comment by UknownGino** [comment] 2023-09-11 14:31
The issue isn't from Rectify 11, the issue comes from lazy developers who still hardcode colors in their applications

**Comment by ooTruffle** [comment] 2023-09-11 23:08
> ![image](https://user-images.githubusercontent.com/65581387/266813637-ae449532-791d-457d-8063-5a080825ef4c.png) Another screenshot, this time on a website, of the bug said before.

What browser
if its chromeium based you need 3rd party css to fix it
if its firefox based its a setting

**Comment by es1228** [comment] 2023-09-11 23:18
Maybe installing dark reader will fix the chrome issues (it’s an extension to add dark theme to every webpage, I also like to use auto dark mode in chrome flags just incase dark reader can’t get everything, but it’s optional)

**Comment by ooTruffle** [comment] 2023-09-12 01:40
Its better to use https://github.com/Rectify11/Installer/issues/127#issuecomment-1537418783 then Dark Reader as it fixes the sites where as dark reader can break certan sites more

Or if your not useing chrome just useing the toggle

**Closed** 2023-10-08 16:15 UTC
Labels: bug
